### ISSUE TITLE
Interceptors / Features?

### ISSUE THREAD

**Issue by ScottPierce** [e5l/http-client-common#9]
I see in the ktor docs that they support something similar to [interceptors](https://github.com/square/okhttp/wiki/Interceptors), but I'm not seeing that in this repo. Am I missing it, or is there no way to intercept / modify requests with this http client? That seems like core functionality for dealing with things like auth, and adding proper auth headers to all requests.

**Comment by e5l** [comment]
Hi, @ScottPierce. It's just a prototype. 
Full-featured ktor is upcoming(hope soon :) ).
